app_office:
    path:     /office
    defaults: { _controller: AppBundle:Default:index }
app_homepublic:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
app_aanbieders:
    path:     /aanbieder/{slug}
    defaults: { _controller: AppBundle:Default:index }
app_producten:
    path:     /office/producten
    defaults: { _controller: AppBundle:Default:index }
app_login:
    path:     /office/profiel
    defaults: { _controller: AppBundle:Default:index }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

users:
    type:     rest
    resource: AppBundle\Controller\UsersController
products:
    type:     rest
    resource: AppBundle\Controller\ProductController
locations:
    type:     rest
    resource: AppBundle\Controller\LocationController

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
